
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FLOWER BISEN
 */
public class booking extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
        
        b12.addMouseListener(this);
        b13.addMouseListener(this);
        b14.addMouseListener(this);
        b15.addMouseListener(this);
        b16.addMouseListener(this);
        b17.addMouseListener(this);
        b18.addMouseListener(this);
        y19.addMouseListener(this);
        y20.addMouseListener(this);
        y21.addMouseListener(this);
        y22.addMouseListener(this);
        y23.addMouseListener(this);
        y24.addMouseListener(this);
        y25.addMouseListener(this);
        y26.addMouseListener(this);
        g3.addMouseListener(this);
        g4.addMouseListener(this);
        g5.addMouseListener(this);
        g6.addMouseListener(this);
        g7.addMouseListener(this);
        g8.addMouseListener(this);
        g9.addMouseListener(this);
        g10.addMouseListener(this);
        gu1.addMouseListener(this);
        gu2.addMouseListener(this);
        gu3.addMouseListener(this);
        gu4.addMouseListener(this);
        gu5.addMouseListener(this);
        gu6.addMouseListener(this);
        gu7.addMouseListener(this);
        gu8.addMouseListener(this);
        gu9.addMouseListener(this);
        gu10.addMouseListener(this);
        gu11.addMouseListener(this);
        gu12.addMouseListener(this);
        r30.addMouseListener(this);
        r31.addMouseListener(this);
        r32.addMouseListener(this);
        vs.addMouseListener(this);
        connect();
    }
        String seatno="";
        int gate=0;
        int price=0;
        
        
        Connection con;
        PreparedStatement pst;
        ResultSet rs;
        
        
        //connecting SQL Database
        
        
        public void connect()
        {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stadium?zeroDateTimeBehavior=convertToNull","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
        
        //Bill Printing
        
        public void Bill()
        {
            String customer=txtcust.getText();
        String seats1=seatno;
        int gaten=gate;
        int pricen=price;
        
        SimpleDateFormat date_form=new SimpleDateFormat("yyyy-MM-dd");
        String date=date_form.format(txtdate.getDate());
        
        
        txtbill.setText(txtbill.getText() +"***********************************************************************************\n");
        txtbill.setText(txtbill.getText() +"************************************Ticket*****************************************\n");
        txtbill.setText(txtbill.getText() +"***********************************************************************************\n");
        txtbill.setText(txtbill.getText() +"Customer Name:"+"\t"+ customer +"\n");
        txtbill.setText(txtbill.getText() +"Seat No.:"+"\t"+ seats1 +"\n");
        txtbill.setText(txtbill.getText() +"Gate:"+"\t"+ gaten +"\n");
        txtbill.setText(txtbill.getText() +"Price:"+"\t"+ pricen +"\n");
        txtbill.setText(txtbill.getText() +"Date:"+"\t"+ date +"\n");
        txtbill.setText(txtbill.getText() +"\n");
        txtbill.setText(txtbill.getText() +"***********************************^^^^^^^^****************************************\n"); 
        txtbill.setText(txtbill.getText() +"**********************************Thank You Come Again***************************************\n");
            
            
            
            
        }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        b12 = new javax.swing.JLabel();
        b13 = new javax.swing.JLabel();
        b14 = new javax.swing.JLabel();
        b15 = new javax.swing.JLabel();
        b16 = new javax.swing.JLabel();
        b17 = new javax.swing.JLabel();
        b18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        g5 = new javax.swing.JLabel();
        g8 = new javax.swing.JLabel();
        g6 = new javax.swing.JLabel();
        g7 = new javax.swing.JLabel();
        g4 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        g9 = new javax.swing.JLabel();
        g10 = new javax.swing.JLabel();
        gu8 = new javax.swing.JLabel();
        gu7 = new javax.swing.JLabel();
        gu6 = new javax.swing.JLabel();
        gu5 = new javax.swing.JLabel();
        gu4 = new javax.swing.JLabel();
        gu3 = new javax.swing.JLabel();
        gu2 = new javax.swing.JLabel();
        gu1 = new javax.swing.JLabel();
        gu12 = new javax.swing.JLabel();
        gu11 = new javax.swing.JLabel();
        gu10 = new javax.swing.JLabel();
        gu9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        y21 = new javax.swing.JLabel();
        y23 = new javax.swing.JLabel();
        y24 = new javax.swing.JLabel();
        y22 = new javax.swing.JLabel();
        y25 = new javax.swing.JLabel();
        y19 = new javax.swing.JLabel();
        y20 = new javax.swing.JLabel();
        y26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        r32 = new javax.swing.JLabel();
        vs = new javax.swing.JLabel();
        r30 = new javax.swing.JLabel();
        r31 = new javax.swing.JLabel();
        book = new javax.swing.JButton();
        txtdate = new com.toedter.calendar.JCalendar();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcust = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 54)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TICKET BOOKING");

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("CUSTOMER");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        b12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        b12.setText("B12");

        b13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        b13.setText("B13");

        b14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        b14.setText("B14");

        b15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        b15.setText("B15");

        b16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        b16.setText("B16");

        b17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        b17.setText("B17");

        b18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        b18.setText("B18");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b12)
                .addGap(18, 18, 18)
                .addComponent(b13)
                .addGap(18, 18, 18)
                .addComponent(b14)
                .addGap(18, 18, 18)
                .addComponent(b15)
                .addGap(18, 18, 18)
                .addComponent(b16)
                .addGap(18, 18, 18)
                .addComponent(b17)
                .addGap(18, 18, 18)
                .addComponent(b18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b12)
                    .addComponent(b13)
                    .addComponent(b14)
                    .addComponent(b15)
                    .addComponent(b16)
                    .addComponent(b17)
                    .addComponent(b18))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        g5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        g5.setText("G5");

        g8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        g8.setText("G8");

        g6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        g6.setText("G6");

        g7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        g7.setText("G7");

        g4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        g4.setText("G4");

        g3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        g3.setText("G3");

        g9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        g9.setText("G9");

        g10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        g10.setText("G10");

        gu8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu8.setText("GU8");

        gu7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu7.setText("GU7");

        gu6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu6.setText("GU6");

        gu5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu5.setText("GU5");

        gu4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu4.setText("GU4");

        gu3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu3.setText("GU3");

        gu2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu2.setText("GU2");

        gu1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu1.setText("GU1");

        gu12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu12.setText("GU12");

        gu11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu11.setText("GU11");

        gu10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu10.setText("GU10");

        gu9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gu9.setText("GU9");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(g3)
                                .addGap(28, 28, 28)
                                .addComponent(g4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(gu1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gu4)
                                .addGap(35, 35, 35)
                                .addComponent(gu5)
                                .addGap(34, 34, 34))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(gu2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gu8)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(gu9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(gu3))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(g5)
                                        .addGap(29, 29, 29)
                                        .addComponent(g6)))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(g7)
                                .addGap(43, 43, 43)
                                .addComponent(g8)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(gu10)
                                .addGap(35, 35, 35)
                                .addComponent(gu11)
                                .addGap(4, 4, 4)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gu6)
                            .addComponent(g9))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(gu7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g10)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(gu12)
                        .addGap(26, 26, 26))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g3)
                    .addComponent(g4)
                    .addComponent(g5)
                    .addComponent(g6)
                    .addComponent(g7)
                    .addComponent(g8)
                    .addComponent(g9)
                    .addComponent(g10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gu1)
                    .addComponent(gu2)
                    .addComponent(gu3)
                    .addComponent(gu4)
                    .addComponent(gu5)
                    .addComponent(gu6)
                    .addComponent(gu7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gu9)
                    .addComponent(gu10)
                    .addComponent(gu11)
                    .addComponent(gu12)
                    .addComponent(gu8))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        y21.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y21.setText("Y21");

        y23.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y23.setText("Y23");

        y24.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y24.setText("Y24");

        y22.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y22.setText("Y22");

        y25.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y25.setText("Y25");

        y19.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y19.setText("Y19");

        y20.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y20.setText("Y20");

        y26.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y26.setText("Y26");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(y19)
                .addGap(18, 18, 18)
                .addComponent(y20)
                .addGap(18, 18, 18)
                .addComponent(y21)
                .addGap(18, 18, 18)
                .addComponent(y22)
                .addGap(18, 18, 18)
                .addComponent(y23)
                .addGap(18, 18, 18)
                .addComponent(y24)
                .addGap(18, 18, 18)
                .addComponent(y25)
                .addGap(18, 18, 18)
                .addComponent(y26)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(y19)
                    .addComponent(y20)
                    .addComponent(y21)
                    .addComponent(y22)
                    .addComponent(y23)
                    .addComponent(y24)
                    .addComponent(y25)
                    .addComponent(y26))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        r32.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        r32.setText("R32");

        vs.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        vs.setText("VISITING SUPPORTERS");

        r30.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        r30.setText("R30");

        r31.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        r31.setText("R31");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r30)
                .addGap(107, 107, 107)
                .addComponent(r31)
                .addGap(99, 99, 99)
                .addComponent(r32)
                .addGap(67, 67, 67))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(vs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r32)
                    .addComponent(r30)
                    .addComponent(r31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(vs)
                .addGap(30, 30, 30))
        );

        book.setBackground(new java.awt.Color(255, 0, 51));
        book.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        book.setText("BOOK");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("------------------------------------------------TICKET----------------------------------------------");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("NORTH STAND");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("EAST STAND");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("WEST STAND");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("SOUTH STAND");

        txtcust.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(162, 162, 162))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcust, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtcust, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
        
        String customer=txtcust.getText();
        String seats1=seatno;
        int gaten=gate;
        int pricen=price;
        
        SimpleDateFormat date_form=new SimpleDateFormat("yyyy-MM-dd");
        String date=date_form.format(txtdate.getDate());
        
        
        //Booking Seats
        
        try {
           
                pst=con.prepareStatement("insert into customer(cname,seatno,price,gate,date)values(?,?,?,?,?)");
                pst.setString(1,customer);
                pst.setString(2,seats1);
                pst.setInt(3,pricen);
                pst.setInt(4,gaten);
                pst.setString(5,date);
                
                int k=pst.executeUpdate();
                
                if(k==1)
                {
                    JOptionPane.showMessageDialog(this,"Seat Booked");
                    Bill();
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Something Wrong");
                }
           
                    
            
            
        } catch (SQLException ex) {
            Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_bookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b13;
    private javax.swing.JLabel b14;
    private javax.swing.JLabel b15;
    private javax.swing.JLabel b16;
    private javax.swing.JLabel b17;
    private javax.swing.JLabel b18;
    private javax.swing.JButton book;
    private javax.swing.JLabel g10;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JLabel g5;
    private javax.swing.JLabel g6;
    private javax.swing.JLabel g7;
    private javax.swing.JLabel g8;
    private javax.swing.JLabel g9;
    private javax.swing.JLabel gu1;
    private javax.swing.JLabel gu10;
    private javax.swing.JLabel gu11;
    private javax.swing.JLabel gu12;
    private javax.swing.JLabel gu2;
    private javax.swing.JLabel gu3;
    private javax.swing.JLabel gu4;
    private javax.swing.JLabel gu5;
    private javax.swing.JLabel gu6;
    private javax.swing.JLabel gu7;
    private javax.swing.JLabel gu8;
    private javax.swing.JLabel gu9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel r30;
    private javax.swing.JLabel r31;
    private javax.swing.JLabel r32;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtcust;
    private com.toedter.calendar.JCalendar txtdate;
    private javax.swing.JLabel vs;
    private javax.swing.JLabel y19;
    private javax.swing.JLabel y20;
    private javax.swing.JLabel y21;
    private javax.swing.JLabel y22;
    private javax.swing.JLabel y23;
    private javax.swing.JLabel y24;
    private javax.swing.JLabel y25;
    private javax.swing.JLabel y26;
    // End of variables declaration//GEN-END:variables

    
    //Conditions according to diff. seats
    
    
    
    @Override
    public void mouseClicked(MouseEvent e) {
        
        
        if(e.getSource()==b12)
        {
            seatno="B12";
            gate=5;
            price=3500;
        }
        
        else if(e.getSource()==b13)
        {
            seatno="B13";
             gate=5;
             price=3500;
        }
        
        else if(e.getSource()==b14)
        {
            seatno="B14";
             gate=5;
             price=3500;
        }
        
        else if(e.getSource()==b15)
        {
            seatno="B15";
             gate=5;
             price=3500;
        }
        
        else if(e.getSource()==b16)
        {
            seatno="B16";
             gate=6;
             price=3500;
        }
        
        else if(e.getSource()==b17)
        {
            seatno="B17";
            gate=6;
            price=3500;
        }
        
        else if(e.getSource()==b18)
        {
            seatno="B18";
            gate=6;
            price=3500;
        }
        
        else if(e.getSource()==y19)
        {
            seatno="Y19";
            gate=7;
            price=5000;
        }
        
        else if(e.getSource()==y20)
        {
            seatno="Y20";
            gate=7;
            price=5000;
        }
        
        else if(e.getSource()==y21)
        {
            seatno="Y21";
            gate=7;
            price=5000;
        }
        
        else if(e.getSource()==y22)
        {
            seatno="Y22";
            gate=7;
            price=5000;
            
        }
        
        else if(e.getSource()==y23)
        {
            seatno="Y23";
            gate=8;
            price=5000;
        }
        
        else if(e.getSource()==y24)
        {
            seatno="Y24";
            gate=8;
            price=5000;
        }
        
        else if(e.getSource()==y25)
        {
            seatno="Y25";
            gate=8;
            price=5000;
        }
        
        else if(e.getSource()==y26)
        {
            seatno="Y26";
            gate=8;
            price=5000;
        }
        
        else if(e.getSource()==g3)
        {
            seatno="G3";
            gate=1;
            price=5000;
        }
        
        else if(e.getSource()==g4)
        {
            seatno="G4";
            gate=1;
            price=5000;
        }
        
        else if(e.getSource()==g5)
        {
            seatno="G5";
            gate=1;
            price=5000;
        }
        
        else if(e.getSource()==g6)
        {
            seatno="G6";
            gate=1;
            price=5000;
        }
        
        else if(e.getSource()==g7)
        {
            seatno="G7";
            gate=4;
            price=5000;
        }
        
        else if(e.getSource()==g8)
        {
            seatno="G8";
            gate=4;
            price=5000;
        }
        
        else if(e.getSource()==g9)
        {
            seatno="G9";
            gate=4;
            price=5000;
        }
        
        else if(e.getSource()==g10)
        {
            seatno="G10";
            gate=4;
            price=5000;
        }
        
        else if(e.getSource()==gu1)
        {
            seatno="GU1";
            gate=2;
            price=4500;
        }
        
        else if(e.getSource()==gu2)
        {
            seatno="GU2";
            gate=2;
            price=4500;
        }
        
        else if(e.getSource()==gu3)
        {
            seatno="GU3";
            gate=2;
            price=4500;
        }
        
        else if(e.getSource()==gu4)
        {
            seatno="GU4";
            gate=2;
            price=4500;
        }
        
        else if(e.getSource()==gu5)
        {
            seatno="GU5";
            gate=2;
            price=4500;
        }
        
        else if(e.getSource()==gu6)
        {
            seatno="GU6";
            gate=2;
            price=4500;
        }
        
        else if(e.getSource()==gu7)
        {
            seatno="GU7";
            gate=3;
            price=4500;
        }
        
        else if(e.getSource()==gu8)
        {
            seatno="GU8";
            gate=3;
            price=4500;
        }
        
        else if(e.getSource()==gu9)
        {
            seatno="GU9";
            gate=3;
            price=4500;
        }
        
        else if(e.getSource()==gu10)
        {
            seatno="GU10";
            gate=3;
            price=4500;
        }
        
        else if(e.getSource()==gu11)
        {
            seatno="GU11";
            gate=3;
            price=4500;
        }
        
        else if(e.getSource()==gu12)
        {
            seatno="GU12";
            gate=3;
            price=4500;
        }
        
        else if(e.getSource()==r30)
        {
            seatno="R30";
            gate=10;
            price=3500;
        }
        
        else if(e.getSource()==r31)
        {
            seatno="R31";
            gate=10;
            price=3500;
        }
        
        else if(e.getSource()==r32)
        {
            seatno="R32";
            gate=10;
            price=3500;
        }
        
        else if(e.getSource()==vs)
        {
            seatno="Visiting Supporters";
            gate=9;
            price=2000;
        }
        
        JOptionPane.showMessageDialog(this,seatno);
    }

    @Override
    public void mousePressed(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
